### ISSUE TITLE
Items about GCS (Ground Control Station)?

### ISSUE THREAD

**Issue by qh-huang** [janesmae/awesome-drones#5]
Great list! I'd like to suggest adding GCSs - they are part of drone technology.

**Comment by janesmae** [comment]
Thanks, any links already to recommend?

**Comment by qh-huang** [comment]
Here are what I found:
* [QGroundControl](https://github.com/mavlink/qgroundcontrol)
* [arduleader](https://github.com/geeksville/arduleader)
* [Tower](https://github.com/DroidPlanner/Tower)
* [MAVProxy](http://ardupilot.github.io/MAVProxy/html/index.html)
* [Mission Planner](https://ardupilot.org/planner/index.html)
* [APM Planner](https://ardupilot.org/planner2)

**Comment by janesmae** [comment]
Thank you, will add them now
